CREATE TABLE BUILDINGS(
PLOT_NUM NUMBER,
CITY NUMBER,
STREET NUMBER,
REN_DATE VARCHAR(20),
OCCUPIED VARCHAR(30),
CONSTRAINT PK_BUILD_1 PRIMARY KEY(PLOT_NUM)
);

CREATE TABLE RESIDENT(
RES_ID NUMBER,
PLOT_NUM NUMBER,
CONSTRAINT PK_RES_1 PRIMARY KEY(RES_ID),
CONSTRAINT FK_PLOT_1 FOREIGN KEY(PLOT_NUM) REFERENCES BUILDINGS(PLOT_NUM)
);

CREATE TABLE HOUSES(
RES_ID NUMBER,
HOUSE_ID NUMBER,
CONSTRAINT PK_H_ID_1 PRIMARY KEY(HOUSE_ID),
CONSTRAINT FK_RES_1 FOREIGN KEY(RES_ID) REFERENCES RESIDENT(RES_ID)
);

CREATE TABLE COMPANY(
CMP_ID NUMBER,
CMP_NAME VARCHAR(20),
CMP_ADD VARCHAR(20),
CONSTRAINT PK_CMP_2 PRIMARY KEY(CMP_ID)
);

CREATE TABLE COMMERCIAL(
CMP_ID NUMBER,
PLOT_NUM NUMBER,
YEAR_LEASE NUMBER,
RENT NUMBER,
CONSTRAINT PK_PLOT_1 PRIMARY KEY(PLOT_NUM),
CONSTRAINT FK_PLOT_3 FOREIGN KEY(PLOT_NUM) REFERENCES BUILDINGS(PLOT_NUM),
CONSTRAINT FK_CMP_2 FOREIGN KEY(CMP_ID) REFERENCES COMPANY(CMP_ID)
);


create table appartments(
appartment_id  NUMBER,
RES_ID  NUMBER,
no_of_Appartments NUMBER,
CONSTRAINT PK_APP_1 PRIMARY KEY(appartment_id),
CONSTRAINT FK_RES_2 FOREIGN KEY(RES_ID) REFERENCES RESIDENT(RES_ID)
);


create table person(
person_name  VARCHAR(20),
email VARCHAR(30),
pwd varchar(30),
CONSTRAINT PK_EMAIL_1 PRIMARY KEY(email)
);

create table SOS(
sos_id NUMBER,
email VARCHAR(30),
CONSTRAINT PK_SOS_1 PRIMARY KEY(sos_id),
CONSTRAINT FK_Email_1 FOREIGN KEY(email) REFERENCES person(email)
);


create table civil_servants(
cs_id NUMBER,
email VARCHAR(30),
scale VARCHAR(20),
status varchar(20),
YOS    NUMBER,
accesstype VARCHAR(20),
HOUSE_ID NUMBER,
appartment_id  NUMBER,
CONSTRAINT PK_CS_1 PRIMARY KEY(cs_id),
CONSTRAINT FK_Email_2 FOREIGN KEY(email) REFERENCES person(email),
CONSTRAINT FK_house_id_2 FOREIGN KEY(house_id) REFERENCES houses(house_id),
CONSTRAINT FK_app_id_2 FOREIGN KEY(appartment_id) REFERENCES appartments(appartment_id)
);









 

